#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${OBTV_SINGLE_ENV_FILE:-${SCRIPT_DIR}/.env}"

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "single-user env file not found: ${ENV_FILE}" >&2
  exit 2
fi

# Exported shell variables outrank Compose --env-file values. Remove both
# production-style names and namespaced single-user names so the audited file
# is the only substitution source.
unset \
  COMPOSE_PROJECT_NAME DATABASE_URL DATABASE_URL_SYNC POSTGRES_PASSWORD \
  ADMIN_USERNAME ADMIN_PASSWORD INTERNAL_API_TOKEN OBTV_HTTP_PORT \
  CURATOR_CLIENT_ID CURATOR_CLIENT_SECRET CURATOR_OAUTH_SCOPE \
  CURATOR_MEDIA_ID_QUERY_FIELD CURATOR_MEDIA_ID_FIELDS \
  CURATOR_WEB_PROXY_FIELDS CURATOR_HIRES_FIELDS CURATOR_HIRES_UNC_PREFIX \
  CURATOR_PROXY_PATH CURATOR_HIRES_PATH IMPORTS_PATH UPLOAD_PATH \
  OBTV_SINGLE_HTTP_PORT OBTV_SINGLE_POSTGRES_PASSWORD \
  OBTV_SINGLE_ADMIN_USERNAME OBTV_SINGLE_ADMIN_PASSWORD \
  OBTV_SINGLE_INTERNAL_API_TOKEN OBTV_SINGLE_CURATOR_CLIENT_ID \
  OBTV_SINGLE_CURATOR_CLIENT_SECRET OBTV_SINGLE_CURATOR_API_BASE_URL \
  OBTV_SINGLE_CURATOR_OAUTH_SCOPE \
  OBTV_SINGLE_CURATOR_MEDIA_ID_QUERY_FIELD \
  OBTV_SINGLE_CURATOR_WEB_PROXY_FIELDS OBTV_SINGLE_CURATOR_HIRES_FIELDS \
  OBTV_SINGLE_CURATOR_HIRES_UNC_PREFIX OBTV_SINGLE_CURATOR_PROXY_PATH \
  OBTV_SINGLE_CURATOR_HIRES_PATH OBTV_SINGLE_IMPORTS_PATH \
  OBTV_SINGLE_UPLOAD_PATH

compose=(
  docker compose
  --project-name obtv-single
  --env-file "${ENV_FILE}"
  -f "${SCRIPT_DIR}/docker-compose.yml"
)

"${compose[@]}" config --format json \
  | python3 "${SCRIPT_DIR}/validate_compose.py"

exec "${compose[@]}" "$@"