import os


DATABASE_URL = os.getenv("DATABASE_URL_SYNC", "postgresql://obtv:obtv@postgres:5432/obtv")
REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")
QDRANT_URL = os.getenv("QDRANT_URL", "http://qdrant:6333")
MEDIA_ROOT = os.getenv("MEDIA_ROOT", "/media")
ARTIFACTS_ROOT = os.getenv("ARTIFACTS_ROOT", "/artifacts")
PROXIES_DIR = os.getenv("PROXIES_DIR", "/artifacts/proxies")
THUMBNAILS_DIR = os.getenv("THUMBNAILS_DIR", "/artifacts/thumbnails")
AUDIO_DIR = os.getenv("AUDIO_DIR", "/artifacts/audio")
REELS_DIR = os.getenv("REELS_DIR", "/artifacts/reels")
RENDERS_DIR = os.getenv("RENDERS_DIR", "/artifacts/renders")
YOUTUBE_CLIENT_ID = os.getenv("YOUTUBE_CLIENT_ID", "")
YOUTUBE_CLIENT_SECRET = os.getenv("YOUTUBE_CLIENT_SECRET", "")
YOUTUBE_REFRESH_TOKEN = os.getenv("YOUTUBE_REFRESH_TOKEN", "")
YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY", "")
SEARXNG_URL = os.getenv("SEARXNG_URL", "")
SERPAPI_KEY = os.getenv("SERPAPI_KEY", "")
TRENDS_REGION = os.getenv("TRENDS_REGION", "US")
DUBS_DIR = os.getenv("DUBS_DIR", "/artifacts/dubs")
VOICES_DIR = os.getenv("VOICES_DIR", "/artifacts/voices")
GRAPHICS_DIR = os.getenv("GRAPHICS_DIR", "/artifacts/graphics")
COMFYUI_URL = os.getenv("COMFYUI_URL", "http://host.docker.internal:8188")
COMFYUI_URL_IMAGE = os.getenv("COMFYUI_URL_IMAGE") or COMFYUI_URL
COMFYUI_URL_VIDEO = os.getenv("COMFYUI_URL_VIDEO") or COMFYUI_URL
COMFY_WORKFLOWS_DIR = os.getenv("COMFY_WORKFLOWS_DIR", "/workflows")
WHISPER_MODEL = os.getenv("WHISPER_MODEL", "large-v3")
EMBEDDINGS_MODEL = os.getenv("EMBEDDINGS_MODEL", "BAAI/bge-m3")
VISION_MODEL = os.getenv("VISION_MODEL", "google/siglip2-so400m-patch14-384")
LLM_MODEL = os.getenv("LLM_MODEL", "Qwen/Qwen3-8B")
TRANSLATE_MODEL = os.getenv("TRANSLATE_MODEL", "google/madlad400-3b-mt")
