import os


DATABASE_URL = os.getenv("DATABASE_URL_SYNC", "postgresql://obtv:obtv@postgres:5432/obtv")
REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")
QDRANT_URL = os.getenv("QDRANT_URL", "http://qdrant:6333")
MEDIA_ROOT = os.getenv("MEDIA_ROOT", "/media")
ARTIFACTS_ROOT = os.getenv("ARTIFACTS_ROOT", "/artifacts")
PROXIES_DIR = os.getenv("PROXIES_DIR", "/artifacts/proxies")
THUMBNAILS_DIR = os.getenv("THUMBNAILS_DIR", "/artifacts/thumbnails")
AUDIO_DIR = os.getenv("AUDIO_DIR", "/artifacts/audio")
REELS_DIR = os.getenv("REELS_DIR", "/artifacts/reels")
RENDERS_DIR = os.getenv("RENDERS_DIR", "/artifacts/renders")
YOUTUBE_CLIENT_ID = os.getenv("YOUTUBE_CLIENT_ID", "")
YOUTUBE_CLIENT_SECRET = os.getenv("YOUTUBE_CLIENT_SECRET", "")
YOUTUBE_REFRESH_TOKEN = os.getenv("YOUTUBE_REFRESH_TOKEN", "")
DUBS_DIR = os.getenv("DUBS_DIR", "/artifacts/dubs")
WHISPER_MODEL = os.getenv("WHISPER_MODEL", "large-v3")
EMBEDDINGS_MODEL = os.getenv("EMBEDDINGS_MODEL", "sentence-transformers/all-MiniLM-L6-v2")
VISION_MODEL = os.getenv("VISION_MODEL", "openai/clip-vit-large-patch14")
LLM_MODEL = os.getenv("LLM_MODEL", "Qwen/Qwen2.5-7B-Instruct")
TRANSLATE_MODEL = os.getenv("TRANSLATE_MODEL", "facebook/nllb-200-distilled-600M")
